[package]
name = "gw-ckb-hardfork"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
smol = "1.2.5"
ckb-types = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }