[package]
name = "gw-tools"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
toml = "0.5"
bech32 = "0.6.0"
tempfile = "3.1"
lazy_static = "1.3"
secp256k1 = "0.19"
sha3 = "0.9.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ckb-jsonrpc-types = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
ckb-types = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
ckb-resource = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
ckb-hash = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
ckb-fixed-hash = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
ckb-sdk = { git = "https://github.com/zzhengzhuo/ckb-cli.git", branch = "v0.100.0-rc1" }
ckb-crypto = { git = "https://github.com/zzhengzhuo/ckb.git", branch = "v0.100.0-rc1" }
gw-db = { path = "../db" }
gw-types = { path = "../types" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
gw-generator = { path = "../generator" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
gw-utils = { path = "../utils" }
gw-rpc-client = { path = "../rpc-client" }
async-jsonrpc-client = { version = "0.3.0", default-features = false, features = ["http-async-std"] }
url = "2.2"
faster-hex = "0.5.0"
rand = "0.8"
hex = "0.4"
smol = "1.2.5"
jsonrpc-core = "17"
